# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vex < Formula
  desc "Beautiful terminal Excel and CSV viewer with vim-style keybindings"
  homepage "https://github.com/CodeOne45/vex-tui"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CodeOne45/vex-tui/releases/download/v2.0.1/vex-tui_2.0.1_darwin_amd64.tar.gz"
      sha256 "cc0a30332a3df0477dce7f64eb12575886eeb1976ad8f88e1723ced9c6e83162"

      def install
        bin.install "vex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CodeOne45/vex-tui/releases/download/v2.0.1/vex-tui_2.0.1_darwin_arm64.tar.gz"
      sha256 "840ff3d54375fa074a6513399f80b0caa2c5c08764d76c774700b6d2ed09e9c5"

      def install
        bin.install "vex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CodeOne45/vex-tui/releases/download/v2.0.1/vex-tui_2.0.1_linux_amd64.tar.gz"
      sha256 "d83d411cd45b4081d170db6e77d38d46e3c341332fad3e59011167ebd2f50e41"
      def install
        bin.install "vex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CodeOne45/vex-tui/releases/download/v2.0.1/vex-tui_2.0.1_linux_arm64.tar.gz"
      sha256 "b5e4f9f73cdfe9f848a370a3c7baff47cae67b55a9a15c7269cd6ed10127d810"
      def install
        bin.install "vex"
      end
    end
  end
end
